import { Metadata } from "next";

export const metadata: Metadata = {
  title: "Privacy Policy | ARGUS Neural Watchman",
  description:
    "How ARGUS secures your Neural DNA and API Vault data using AES-256 encryption.",
};

export default function PrivacyPage() {
  return (
    <div className="min-h-screen bg-slate-950 text-slate-300">
      <div className="max-w-4xl mx-auto py-20 px-6">
        {/* Header */}
        <div className="mb-12 pb-8 border-b border-slate-800">
          <h1 className="text-4xl font-black text-white tracking-tighter uppercase mb-4">
            Privacy Policy
          </h1>
          <p className="text-sm text-blue-500 font-mono uppercase tracking-wider">
            Effective Date: January 9, 2026
          </p>
          <p className="text-xs text-slate-500 mt-2 font-mono">
            ARGUS_NEURAL_WATCHMAN_v1.2.0_STABLE
          </p>
        </div>

        <div className="space-y-12 leading-relaxed">
          {/* Introduction */}
          <section>
            <h2 className="text-xl font-bold text-white uppercase tracking-tight mb-4">
              Introduction
            </h2>
            <p className="text-slate-400">
              ARGUS Neural Watchman (&quot;ARGUS,&quot; &quot;we,&quot;
              &quot;us,&quot; or &quot;our&quot;) is committed to protecting
              your privacy. This Privacy Policy explains how we collect, use,
              store, and protect your information when you use our AI-powered
              test automation platform.
            </p>
          </section>

          {/* 1. Information We Collect */}
          <section>
            <h2 className="text-xl font-bold text-white uppercase tracking-tight mb-4">
              1. Information We Collect
            </h2>

            <h3 className="text-base font-bold text-slate-200 mb-3 mt-4">
              1.1 Account Information
            </h3>
            <p className="text-slate-400 mb-3">
              We collect information provided during account registration via
              Clerk authentication:
            </p>
            <ul className="list-disc list-inside space-y-2 text-slate-400 ml-4">
              <li>Email address</li>
              <li>Username or display name</li>
              <li>Authentication provider data (Google, GitHub, etc.)</li>
              <li>User ID (generated by authentication service)</li>
            </ul>

            <h3 className="text-base font-bold text-slate-200 mb-3 mt-4">
              1.2 Encrypted API Credentials
            </h3>
            <p className="text-slate-400 mb-3">
              When you configure the System Vault, we store encrypted versions
              of:
            </p>
            <ul className="list-disc list-inside space-y-2 text-slate-400 ml-4">
              <li>OpenAI API keys</li>
              <li>Google Gemini API keys</li>
              <li>Groq API keys</li>
              <li>Anthropic API keys</li>
              <li>Perplexity API keys</li>
              <li>Preferred AI provider selection</li>
            </ul>
            <div className="bg-blue-500/10 border border-blue-500/30 rounded-lg p-4 mt-3">
              <p className="text-blue-400 text-sm font-bold mb-2">
                Zero-Knowledge Architecture
              </p>
              <p className="text-slate-300 text-sm">
                All API keys undergo{" "}
                <span className="font-mono text-blue-400">AES-256-CBC</span>{" "}
                encryption at the client-side before transmission. We never see
                or store your keys in plain text. If your{" "}
                <span className="font-mono">VAULT_MASTER_KEY</span> is lost,
                recovery is mathematically impossible.
              </p>
            </div>

            <h3 className="text-base font-bold text-slate-200 mb-3 mt-4">
              1.3 Test Execution Data
            </h3>
            <p className="text-slate-400 mb-3">
              During test runs, we collect and store:
            </p>
            <ul className="list-disc list-inside space-y-2 text-slate-400 ml-4">
              <li>Target URLs and test intents</li>
              <li>Execution logs (actions, selectors, status codes)</li>
              <li>
                DOM fingerprints (element selectors, attributes, inner text)
              </li>
              <li>Test configuration parameters</li>
              <li>Timestamps and execution duration</li>
              <li>Test success/failure rates</li>
            </ul>

            <h3 className="text-base font-bold text-slate-200 mb-3 mt-4">
              1.4 Usage Analytics
            </h3>
            <p className="text-slate-400">
              We collect anonymized usage data including feature adoption, error
              rates, and performance metrics to improve service quality.
            </p>
          </section>

          {/* 2. How We Use Your Information */}
          <section>
            <h2 className="text-xl font-bold text-white uppercase tracking-tight mb-4">
              2. How We Use Your Information
            </h2>
            <p className="text-slate-400 mb-3">
              We use collected information for the following purposes:
            </p>
            <ul className="list-disc list-inside space-y-2 text-slate-400 ml-4">
              <li>
                <strong>Service Delivery:</strong> Execute AI-powered test
                automation on your behalf
              </li>
              <li>
                <strong>Self-Healing:</strong> Analyze execution logs to
                automatically repair brittle selectors
              </li>
              <li>
                <strong>Risk Analysis:</strong> Generate Predictive Risk
                Heatmaps based on historical test stability
              </li>
              <li>
                <strong>Authentication:</strong> Verify user identity and manage
                sessions
              </li>
              <li>
                <strong>Support:</strong> Troubleshoot issues and respond to
                inquiries
              </li>
              <li>
                <strong>Compliance:</strong> Detect and prevent unauthorized or
                malicious usage
              </li>
              <li>
                <strong>Improvement:</strong> Enhance platform features and
                performance
              </li>
            </ul>
          </section>

          {/* 3. Data Storage & Security */}
          <section>
            <h2 className="text-xl font-bold text-white uppercase tracking-tight mb-4">
              3. Data Storage & Security
            </h2>

            <h3 className="text-base font-bold text-slate-200 mb-3 mt-4">
              3.1 Infrastructure
            </h3>
            <p className="text-slate-400 mb-3">
              Your data is stored and processed using the following trusted
              infrastructure:
            </p>
            <ul className="list-disc list-inside space-y-2 text-slate-400 ml-4">
              <li>
                <strong>Database:</strong> Supabase (PostgreSQL with Row Level
                Security)
              </li>
              <li>
                <strong>Hosting:</strong> Vercel (Next.js 16 frontend)
              </li>
              <li>
                <strong>Worker:</strong> Hugging Face Spaces (Python execution
                environment)
              </li>
              <li>
                <strong>Authentication:</strong> Clerk (third-party identity
                provider)
              </li>
            </ul>

            <h3 className="text-base font-bold text-slate-200 mb-3 mt-4">
              3.2 Security Measures
            </h3>
            <ul className="list-disc list-inside space-y-2 text-slate-400 ml-4">
              <li>AES-256-CBC encryption for all sensitive credentials</li>
              <li>
                Row Level Security (RLS) policies isolate user data in the
                database
              </li>
              <li>HTTPS/TLS encryption for all data in transit</li>
              <li>Regular security audits and dependency updates</li>
              <li>No plain-text storage of API keys or passwords</li>
            </ul>

            <h3 className="text-base font-bold text-slate-200 mb-3 mt-4">
              3.3 Data Retention
            </h3>
            <p className="text-slate-400">
              We retain execution logs and test data for 90 days or until you
              delete them manually. Account data is retained until account
              deletion is requested.
            </p>
          </section>

          {/* 4. Data Sharing */}
          <section>
            <h2 className="text-xl font-bold text-white uppercase tracking-tight mb-4">
              4. Data Sharing & Third Parties
            </h2>

            <h3 className="text-base font-bold text-slate-200 mb-3 mt-4">
              4.1 AI Provider Processing
            </h3>
            <p className="text-slate-400 mb-3">
              Your test execution data (URLs, intents, DOM content) is
              transmitted to your selected AI provider:
            </p>
            <ul className="list-disc list-inside space-y-2 text-slate-400 ml-4">
              <li>OpenAI (GPT models)</li>
              <li>Google (Gemini models)</li>
              <li>Groq (Llama models)</li>
              <li>Anthropic (Claude models)</li>
              <li>Perplexity (Sonar models)</li>
            </ul>
            <p className="text-slate-400 mt-3">
              Each provider processes data according to their own privacy
              policies. We recommend reviewing their policies before use.
            </p>

            <h3 className="text-base font-bold text-slate-200 mb-3 mt-4">
              4.2 No Data Sales
            </h3>
            <p className="text-slate-400">
              We <strong>do not sell</strong> your personal information,
              execution logs, or telemetry data to third-party brokers or
              advertisers. Your data is siloed per user and never used for
              multi-tenant model training.
            </p>

            <h3 className="text-base font-bold text-slate-200 mb-3 mt-4">
              4.3 Legal Compliance
            </h3>
            <p className="text-slate-400">
              We may disclose information if required by law, court order, or to
              prevent illegal activities such as unauthorized penetration
              testing or DDoS attacks.
            </p>
          </section>

          {/* 5. Your Rights */}
          <section>
            <h2 className="text-xl font-bold text-white uppercase tracking-tight mb-4">
              5. Your Privacy Rights
            </h2>
            <p className="text-slate-400 mb-3">
              You have the following rights regarding your data:
            </p>
            <ul className="list-disc list-inside space-y-2 text-slate-400 ml-4">
              <li>
                <strong>Access:</strong> View all data we store about you
              </li>
              <li>
                <strong>Deletion:</strong> Delete your account and all
                associated data
              </li>
              <li>
                <strong>Correction:</strong> Update inaccurate account
                information
              </li>
              <li>
                <strong>Export:</strong> Download execution logs and test
                configurations
              </li>
              <li>
                <strong>Opt-Out:</strong> Disable analytics or telemetry
                collection
              </li>
            </ul>
            <p className="text-slate-400 mt-3">
              To exercise these rights, contact us at{" "}
              <span className="text-blue-500 font-mono">
                privacy@argus-watchman.ai
              </span>
            </p>
          </section>

          {/* 6. Cookies & Tracking */}
          <section>
            <h2 className="text-xl font-bold text-white uppercase tracking-tight mb-4">
              6. Cookies & Tracking Technologies
            </h2>
            <p className="text-slate-400 mb-3">We use the following cookies:</p>
            <ul className="list-disc list-inside space-y-2 text-slate-400 ml-4">
              <li>
                <strong>Authentication Cookies:</strong> Managed by Clerk to
                maintain login sessions
              </li>
              <li>
                <strong>Session Cookies:</strong> Temporary tokens for form
                state and CSRF protection
              </li>
              <li>
                <strong>Analytics Cookies:</strong> Anonymized usage metrics
                (optional, can be disabled)
              </li>
            </ul>
            <p className="text-slate-400 mt-3">
              You can disable cookies in your browser settings, but this may
              impact functionality.
            </p>
          </section>

          {/* 7. International Data Transfers */}
          <section>
            <h2 className="text-xl font-bold text-white uppercase tracking-tight mb-4">
              7. International Data Transfers
            </h2>
            <p className="text-slate-400">
              ARGUS operates globally. Your data may be transferred to and
              processed in countries outside your residence. We ensure
              appropriate safeguards are in place to protect your data in
              compliance with applicable privacy laws.
            </p>
          </section>

          {/* 8. Children's Privacy */}
          <section>
            <h2 className="text-xl font-bold text-white uppercase tracking-tight mb-4">
              8. Children&apos;s Privacy
            </h2>
            <p className="text-slate-400">
              ARGUS is not intended for users under 18 years of age. We do not
              knowingly collect information from minors. If you believe a child
              has provided us with personal information, contact us immediately
              for deletion.
            </p>
          </section>

          {/* 9. Changes to Policy */}
          <section>
            <h2 className="text-xl font-bold text-white uppercase tracking-tight mb-4">
              9. Changes to This Policy
            </h2>
            <p className="text-slate-400">
              We may update this Privacy Policy periodically. Changes will be
              posted on this page with an updated effective date. Continued use
              of ARGUS after changes constitutes acceptance of the revised
              policy.
            </p>
          </section>

          {/* Contact */}
          <section className="pt-8 border-t border-slate-800">
            <h2 className="text-xl font-bold text-white uppercase tracking-tight mb-4">
              Contact Us
            </h2>
            <p className="text-slate-400 mb-2">
              For privacy-related inquiries, data requests, or concerns:
            </p>
            <p className="text-blue-500 font-mono text-sm">
              privacy@argus-watchman.ai
            </p>
          </section>
        </div>

        {/* Footer */}
        <div className="mt-16 pt-8 border-t border-slate-900 text-center">
          <p className="text-xs text-slate-600 font-mono uppercase tracking-widest">
            ARGUS Neural Watchman © 2026 • All Rights Reserved
          </p>
        </div>
      </div>
    </div>
  );
}
