from enum import Enum
from typing import List, Optional, Dict, Any
from pydantic import BaseModel, Field

class Role(str, Enum):
    CUSTOMER = "customer"
    ADMIN = "admin"
    SYSTEM = "system"
    CRAWLER = "crawler"

class ActionType(str, Enum):
    """
    Standardized Actions.
    Synchronized with PLANNER_SYSTEM_PROMPT and AutomationRunner.
    """
    NAVIGATE = "navigate"
    CLICK = "click"
    INPUT = "input"
    VERIFY_TEXT = "verify_text"
    EXTRACT_TEXT = "extract_text"
    SCREENSHOT = "screenshot"
    WAIT = "wait"
    RELOAD = "reload"

class ElementFingerprint(BaseModel):
    """
    Structural DNA of a UI element.
    Synchronized with public.element_fingerprints table.
    """
    tag_name: str = Field(..., alias="tag") # Aligned with Supabase column
    inner_text: Optional[str] = Field(None, alias="text") # Aligned with Supabase column
    attributes: Dict[str, Any] = {}
    xpath: Optional[str] = None
    location: Dict[str, float] = {"x": 0, "y": 0}

    class Config:
        allow_population_by_field_name = True

class TestStep(BaseModel):
    """
    A single atomic unit of work within a mission.
    """
    step_id: int
    role: Role = Role.CUSTOMER
    action: ActionType
    description: str
    selector: Optional[str] = None
    value: Optional[str] = None

    # Metadata for Healing & Reporting
    details: Optional[str] = "" # Explains the 'Why' behind the action or failure
    key_to_extract: Optional[str] = None
    fingerprint: Optional[ElementFingerprint] = None # Captured DNA for self-healing

    # Score for the RiskAnalyzer
    complexity_score: int = 5

class TestPlan(BaseModel):
    """
    The full execution blueprint generated by the Planner.
    """
    intent: str
    steps: List[TestStep]
    is_chaos_mode: bool = False # Triggers adversarial logic in the Runner
    target_url: Optional[str] = None # Anchors the navigation
