from enum import Enum
from typing import List, Optional, Any
from pydantic import BaseModel, Field

class Role(str, Enum):
    """Defines the user persona executing the action."""
    CUSTOMER = "customer"
    ADMIN = "admin"
    SYSTEM = "system"

class ActionType(str, Enum):
    """Strict dictionary of allowed browser actions."""
    NAVIGATE = "navigate"
    CLICK = "click"
    INPUT = "input"
    VERIFY_TEXT = "verify_text"
    EXTRACT_TEXT = "extract_text"  # For grabbing IDs like order numbers
    SCREENSHOT = "screenshot"
    WAIT = "wait"

class TestStep(BaseModel):
    """Atomic unit of a test plan."""
    step_id: int = Field(..., description="Sequential ID of the step")
    role: Role = Field(..., description="Who performs this action")
    action: ActionType = Field(..., description="The specific tool to use")
    description: str = Field(..., description="Human-readable explanation of why")

    # Action Parameters (Optional based on action type)
    selector: Optional[str] = Field(None, description="CSS or XPath selector")
    value: Optional[str] = Field(None, description="Text to input or expected value to verify")
    key_to_extract: Optional[str] = Field(None, description="Variable name to save extracted data to (e.g. 'order_id')")

class TestPlan(BaseModel):
    """The complete blueprint generated by the AI."""
    intent: str = Field(..., description="The original business intent")
    steps: List[TestStep] = Field(..., description="Ordered list of execution steps")
